---
title: "gapminder_analysis"
author: "Elinor Lichtenberg"
date: "10/4/2015"
output: html_document
---
We are working with the file combined_gapMinder.tsv.
```{r setup, echo=F}
#Get data
gap.in <- read.table("output//combined_gapMinder.tsv", header=T, sep="\t")

#Load library
library(dplyr)
```

The countries in this file are:
```{r see-countries, echo=FALSE}
levels(gap.in$country)
```

```{r limit_countries, echo=FALSE}
#Pick the 3 countries I want to use
gap.3 <- filter(gap.in, country %in% c("Brazil", "Guinea", "United States")) %>% droplevels()
```

There are distinct trends in GDP over time in `r levels(gap.3$country)`. GDP increases in all three countries, but is sadly small in Guinea.
```{r GDP-plots, echo=FALSE}
#Plot GDP as a function of year
par(mfrow=c(1, 3))
with(filter(gap.3, country=="Brazil"), plot(year, gdpPercap, main="Brazil", xlab="Year", ylab="Per capita GDP", bty="n"))
with(filter(gap.3, country=="Guinea"), plot(year, gdpPercap, main="Guinea", xlab="Year", ylab="Per capita GDP", bty="n"))
with(filter(gap.3, country=="United States"), plot(year, gdpPercap, main="United States", xlab="Year", ylab="Per capita GDP", bty="n"))
```

Now let's look at life expectancy by continent.
```{r life-expect-cont, echo=FALSE}
lives <- gap.in %>%
  group_by(continent) %>%
  summarise(mean_expectancy=mean(lifeExp), min_expectancy=min(lifeExp), max_expectancy=max(lifeExp))
print(lives)
```

Distribution of global life expectancy:

```{r life-expect-global, echo=FALSE}

hist(gap.in$lifeExp, main="Default bins", xlab="Life expectancy (years)")
default.breaks <- nclass.Sturges(gap.in$lifeExp)
hist(gap.in$lifeExp, breaks=default.breaks*2, main="Narrower bins", xlab="Life expectancy (years)")

```